services:
  bookseerr:
    build: ./bookseerr
    container_name: bookseerr
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - /path/to/downloads:/downloads
      - /path/to/library:/library
      - /path/to/data:/data
    restart: unless-stopped
